
package proyectomail;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author ferefrapb
 */
public class accesoAlSistema extends javax.swing.JFrame {

    public accesoAlSistema() throws ClassNotFoundException, SQLException {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        BDD.getInstancia().conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Acceso Al Sistema");

        jLabel2.setText("Usuario");

        jLabel3.setText("Password");

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectomail/LOGO_MEIA2 (2).png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Corrupted Data Mail");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnIngresar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresar)
                            .addComponent(jButton1)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarAlSistema(String User)
    {
        
        File pathFolderMEIA = new File("C:\\MEIA");
                String strPath = pathFolderMEIA + "/Usuario.txt";
                String strError;
                boolean usuarioYPasswordCorrecto = false;
                File ArchivoUsuariosTxt = new File(strPath);
                
                FileReader LecturaArchivo;
                try {
                    LecturaArchivo = new FileReader(ArchivoUsuariosTxt);
                    BufferedReader LeerArchivo = new BufferedReader(LecturaArchivo);
                    String Linea="";
                    try {
                        Linea=LeerArchivo.readLine();
                        String[] split;
                        Usuario objUsuarioArchivo = new Usuario(User);
                        if (Linea=="")
                        {
                            // Crear primer usuario de este programa

                            LecturaArchivo.close();
                            LeerArchivo.close();
                        }
                        else
                        {
                            String lineaAEscribir = "";
                            while(Linea != null)
                            {
                                if(Linea!="")
                                {
                                    
                                    split=Linea.split("\\|");
                                    String usuarioComp=txtUsuario.getText();
                                    if(split[0].equals(usuarioComp))
                                    {
                                        if(split[9].equals("1"))
                                        {
                                        menuAdmin objFormNuevo = new menuAdmin();
                                        objFormNuevo.setVisible(true);
                                        for(int i = 0; i< split.length; i++)
                                        {
                                            if(i ==8)
                                            {
                                                ImageIcon imagen = new ImageIcon(split[8].toString());
                                                Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(objFormNuevo.getWidth(),objFormNuevo.getHeight(),Image.SCALE_DEFAULT));   
                                                objFormNuevo.lblFoto.setIcon(icono);
                                            }
                                            else
                                            {
                                                if((i != 0)&(i!=3)&(i!=4)&(i!=9) )
                                                {
                                                    lineaAEscribir += split[i].toString() + "\n";  
                                                }
                                                              
                                            }
                                            
                                        }
                                        objFormNuevo.txtNombre.setText(split[0]);
                                        objFormNuevo.txtMostrarInfo.setText(lineaAEscribir);
                                        objFormNuevo.lblRol.setText(split[4]);
                                    }
                                    if(split[9].equals("0"))
                                    {
                                        menuUsuario objFormNuevo = new menuUsuario();
                                        objFormNuevo.setVisible(true);
                                        for(int i = 0; i< split.length; i++)
                                        {
                                            if(i ==8)
                                            {
                                                ImageIcon imagen = new ImageIcon(split[8].toString());
                                                Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(objFormNuevo.getWidth(),objFormNuevo.getHeight(),Image.SCALE_DEFAULT));   
                                                objFormNuevo.lblFoto.setIcon(icono);
                                            }
                                            else
                                            {
                                                if((i != 0)&(i!=3)&(i!=4)&(i!=9) )
                                                {
                                                    lineaAEscribir += split[i].toString() + "\n";  
                                                }
                                            }
                                            
                                        }
                                        objFormNuevo.txtNombre.setText(split[0]);
                                        objFormNuevo.txtMostrarInfo.setText(lineaAEscribir);
                                        objFormNuevo.lblRol.setText(split[4]);
                                    }
                                    }
                                    
                                }
                                Linea=LeerArchivo.readLine();
                            }  
                        }

                        LecturaArchivo.close();
                        LeerArchivo.close();

                        //listaNombre.setModel(modeloNombre);
                        //listaApellido.setModel(modeloApellido);
                        strError="";
                        //return true;

                    } catch (IOException ex) {
                        strError= ex.getMessage().toString();
                        //return false;
                    }
            } catch (FileNotFoundException ex) {
                strError= ex.getMessage().toString();
                //return false;
            } 
    }
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // Boton de Ingreso al sistema
        
        String cadenaUsuario = txtUsuario.getText();
        char[] ps1=txtPassword.getPassword();
        String cadenaPassword = String.valueOf(ps1);
        Usuario objUsuario = new Usuario(cadenaUsuario);
        objUsuario.usuario=cadenaUsuario;
        objUsuario.password=cadenaPassword;
        
        manejadorArchivo archivoUsuario = new manejadorArchivo();
       
        if (archivoUsuario.verificarArchivoExiste()) 
        {
            if (archivoUsuario.verificarUsuarioYPassword(objUsuario)) 
            {
                String User = objUsuario.usuario;
                //metodo para entrar al sistema segun sea admin o usuario
                entrarAlSistema(User);     
                
                
               
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Su usuario y/o password estan incorrectos o no existen en el sistema\nPorfavor ingreselos de nuevo");
                txtUsuario.setText("");
                txtPassword.setText("");
                txtUsuario.requestFocus();
            }    
        }
        else
        {
            // Crear archivos
            JOptionPane.showMessageDialog(rootPane, "Por ser el primer usuario, por defecto sera el administrador");
            nuevoUsuario objFormNuevoUsuario=new nuevoUsuario();
            objFormNuevoUsuario.setVisible(true);

        }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            BDD.getInstancia().Insert(9, 2, "lp", "Alexrod9", "asunto", "mensaje");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(accesoAlSistema.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(accesoAlSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accesoAlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accesoAlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accesoAlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accesoAlSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new accesoAlSistema().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(accesoAlSistema.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(accesoAlSistema.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
