/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomail;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author luisp
 */
public class BandejaEntrada extends javax.swing.JFrame {

    Usuario User;
    String usuario ="";
    ArbolBinario Arbolito;
    
    public BandejaEntrada(String Usuario) throws IOException {
        this.usuario = Usuario.trim();
        initComponents();
        lUsuario.setText(this.usuario);
        User = new Usuario(this.usuario);
        Arbolito = new ArbolBinario("C:\\MEIA\\Mensajes.txt", "Izquierda|Derecha|Receptor|Emisor|Fecha|Mensaje|Estatus", "|");
        this.setLocationRelativeTo(null);
        ActualizarBandeja();
        try
        {
            boolean Bandera=true;
            int i=0;
            jBandejaEntrada.setText("");
            if(!lUsuario.getText().isEmpty()){
                while(Bandera && i < User.MensajesRecibidos.size())
                {
                    /*if(User.MensajesRecibidos.get(i)[0].equals(lUsuario.getText().trim()))
                    {*/
                        if (jBandejaEntrada.getText().length()!=0)
                        {
                            jBandejaEntrada.append("\n\r"+"\n\r");
                        }
                        jBandejaEntrada.append(User.MensajesRecibidos.get(i)[0]+":\n\r"+User.MensajesRecibidos.get(i)[2]+"\n\r"+User.MensajesRecibidos.get(i)[1]);
                    /*}
                    else
                    {*/
                        if (!jBandejaEntrada.getText().equals(""))
                        {
                            Bandera=false;
                        }
                    /*}*/
                    i++;
                }
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensaje de Error", JOptionPane.ERROR_MESSAGE, null);
        }
    }

    private void ActualizarBandeja()
    {
        try
        {
            String[] linea;
            User.MensajesRecibidos=Arbolito.ObtenerMensajes(lUsuario.getText());
            for (int i = 0; i < User.MensajesRecibidos.size(); i++) 
            {
                linea=User.MensajesRecibidos.get(i);
            }
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Mensaje de Error", JOptionPane.ERROR_MESSAGE, null);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBandejaEntrada = new javax.swing.JTextArea();
        bActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lUsuario.setText("Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bandeja de Entrada");

        jBandejaEntrada.setColumns(20);
        jBandejaEntrada.setRows(5);
        jScrollPane1.setViewportView(jBandejaEntrada);

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bActualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        ActualizarBandeja();
        boolean Bandera=true;
        int i=0;
        jBandejaEntrada.setText("");
        if(!lUsuario.getText().isEmpty()){
                while(Bandera && i < User.MensajesRecibidos.size())
                {
                    /*if(User.MensajesRecibidos.get(i)[0].equals(lUsuario.getText().trim()))
                    {*/
                        if (jBandejaEntrada.getText().length()!=0)
                        {
                            jBandejaEntrada.append("\n\r"+"\n\r");
                        }
                        jBandejaEntrada.append(User.MensajesRecibidos.get(i)[0]+":\n\r"+User.MensajesRecibidos.get(i)[2]+"\n\r"+User.MensajesRecibidos.get(i)[1]);
                    /*}
                    else
                    {*/
                        if (!jBandejaEntrada.getText().equals(""))
                        {
                            Bandera=false;
                        }
                    /*}*/
                    i++;
                }
            }
        
    }//GEN-LAST:event_bActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BandejaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BandejaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BandejaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BandejaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BandejaEntrada().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JTextArea jBandejaEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lUsuario;
    // End of variables declaration//GEN-END:variables
}
