/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomail;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ferefrapb
 */
public class nuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form nuevoUsuario
     */
    public nuevoUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        txtPassword2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        labelcorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPathFotografia = new javax.swing.JTextField();
        btnFotografia = new javax.swing.JButton();
        btnRegistrarNuevoUsuario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblRango = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblComprobarTel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Password");

        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });
        txtPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassword1KeyTyped(evt);
            }
        });

        txtPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassword2MouseClicked(evt);
            }
        });
        txtPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassword2KeyTyped(evt);
            }
        });

        jLabel5.setText("Verificacion Password");

        txtFechaNacimiento.setText("dd/mm/aaaa");

        jLabel6.setText("Fecha Nacimiento");

        labelcorreo.setText("Correo Electrónico");

        jLabel8.setText("Teléfono");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel9.setText("Seleccionar Fotografía");

        btnFotografia.setText("Seleccionar");
        btnFotografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotografiaActionPerformed(evt);
            }
        });

        btnRegistrarNuevoUsuario.setText("Registrar Nuevo Usuario");
        btnRegistrarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoUsuarioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel11.setText("Registro Nuevo Usuario");

        lblRango.setEditable(false);
        lblRango.setBackground(new java.awt.Color(204, 204, 204));
        lblRango.setFocusable(false);
        jScrollPane2.setViewportView(lblRango);

        jScrollPane3.setEnabled(false);
        jScrollPane3.setFocusable(false);

        lblComprobarTel.setEditable(false);
        jScrollPane3.setViewportView(lblComprobarTel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel11)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre)
                        .addComponent(txtApellido)
                        .addComponent(txtUsuario)
                        .addComponent(txtPassword1)
                        .addComponent(txtPassword2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelcorreo)
                    .addComponent(jLabel8)
                    .addComponent(txtCorreo)
                    .addComponent(txtTelefono)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPathFotografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFotografia))
                    .addComponent(btnRegistrarNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelcorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPathFotografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFotografia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        
    }//GEN-LAST:event_txtPassword1ActionPerformed

    private void btnRegistrarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoUsuarioActionPerformed
    
    Usuario objUsuario= new Usuario();
    manejadorArchivo objManejadorArchivo = new manejadorArchivo();
    
    
    String usuario = txtUsuario.getText();
    String nombre = txtNombre.getText();
    String apellido = txtApellido.getText();
    char[] ps1 = txtPassword1.getPassword();
    String password1 = String.valueOf(ps1);
    char[] ps2 = txtPassword2.getPassword();
    String password2 = String.valueOf(ps2);
    int rol=0;
    String fechaNacimiento = txtFechaNacimiento.getText();
    String correo = txtCorreo.getText();
    String tempTel=txtTelefono.getText();
    String pathFotografia = txtPathFotografia.getText();
    //String descripcion = txtdescripcion.getText();
    int estatus=1;
    
        if (!(usuario.equals(""))&&!(nombre.equals(""))&&!(apellido.equals(""))&&!(password1.equals(""))&&!( password2.equals(""))&&!(fechaNacimiento=="dd/mm/aaaa")&&!(correo.equals(""))&&!(tempTel.equals(""))&&!(pathFotografia.equals("")))
        {
            if (password1.equals(password2))
            {
                
                
                objUsuario.usuario = usuario;

                //Este if Comprueba si en el archivo hay algun nombre de usuario que ya se utilizo
                if (!objManejadorArchivo.getBanderaUsuarioExistente())
                {
                    // Comrpueba que el passwrod cumpla con los estandares
                    if (ComprobacionPassword())
                    {
                        if (comprobarTelefono()) 
                        {
                        int telefono = Integer.parseInt(txtTelefono.getText());
                        objUsuario.nombre = nombre;
                        objUsuario.apellido = apellido;
                        objUsuario.password = password1;
                        //objUsuario.rol=rol;
                        objUsuario.fechaNacimiento = fechaNacimiento;
                        objUsuario.correo = correo;
                        objUsuario.telefono = telefono;
                        objUsuario.pathFotografia = pathFotografia;
                        //objUsuario.descripcion = descripcion;
                        objUsuario.estatus=1;
                        
                            if (objManejadorArchivo.verificarArchivoExiste())
                            {
                                
                                // Crear nuevo usuario y añadirlo a la bitacora
                                objUsuario.rol=0;
                             objManejadorArchivo.escribirArchivoBitacora(objUsuario);
                             objManejadorArchivo.escribirUsuario(objUsuario);
                             //Verificar que el usuario no exista   
                                
                                
                            }
                            else
                            {
                                 // Crear nuevo usuario ADMINISTRADOR y añadirlo a la bitacora
                                objUsuario.rol=1;
                                objManejadorArchivo.crearArchivosDelSistema(objUsuario);
                                objManejadorArchivo.escribirArchivoBitacora(objUsuario);
                                objManejadorArchivo.escribirUsuario(objUsuario);
                                //Verificar que el usuario no exista
                                
                            }
 
                        }
                        else
                        {
                        JOptionPane.showMessageDialog(rootPane, "Ingreso un numero de telefono NO VALIDO");
                        txtTelefono.setText("");
                        txtTelefono.requestFocus();
                        }  
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "La contraseña ingresada es insegura, ingrese una contraseña que cumpla con los estandares");
                        txtPassword1.setText("");
                        txtPassword2.setText("");
                        txtPassword1.requestFocus();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "El usuario "+ objUsuario.usuario + " esta en uso, porfavor ingrese otro nombre de usuario");
                    txtUsuario.setText("");
                    txtUsuario.requestFocus();
                } 
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "La contraseñas no son iguales vuelva a ingresarlas");
                txtPassword1.setText("");
                txtPassword2.setText("");
                txtPassword1.requestFocus();
            }
            JOptionPane.showMessageDialog(rootPane, "Usuario Ingresado");
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese todos los campos requeridos");
        }
    }//GEN-LAST:event_btnRegistrarNuevoUsuarioActionPerformed

    private void txtPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassword2MouseClicked
    
    }//GEN-LAST:event_txtPassword2MouseClicked

    private void txtPassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword1KeyTyped
        ComprobacionPassword();
    }//GEN-LAST:event_txtPassword1KeyTyped

    private void txtPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword2KeyTyped
  
    }//GEN-LAST:event_txtPassword2KeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        if (comprobarTelefono()) 
        {
            lblComprobarTel.setText("Numero Valido");
            lblComprobarTel.setForeground(Color.green);
        }
        else
        {
            lblComprobarTel.setText("Numero Ingresado no valido");
            lblComprobarTel.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnFotografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotografiaActionPerformed
        JFileChooser dialogo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter ("Imagen", "jpg");
        File ficheroImagen;
        String rutaArchivo;
        dialogo.setFileFilter(filtro);
        int valor = dialogo.showOpenDialog(this);
        if(valor == JFileChooser.APPROVE_OPTION)
        {
        ficheroImagen = dialogo.getSelectedFile();
        rutaArchivo = ficheroImagen.getPath();
        
        txtPathFotografia.setText(rutaArchivo);
        }
    }//GEN-LAST:event_btnFotografiaActionPerformed

    private boolean comprobarTelefono()
    {
        String cadena =txtTelefono.getText();
        int numNumeros =0;
            for (int i = 0; i < cadena.length(); i++) 
            {
                char c;
                c=cadena.charAt(i);
                if (Character.isDigit(c))
                {
                    numNumeros++;
                } 
            }
            if (numNumeros==cadena.length()) 
            {
                return true;
            }
            else
            {
                return false;
            }
    }
    private boolean ComprobacionPassword()
    {
        char[] cadena1 = txtPassword1.getPassword();
        //String cadena=txtPassword1.getPassword().toString();
        String cadena= String.valueOf(cadena1);
        boolean banderaPassword=false;        
        
        int puntuacion=0;
        
        
        if (cadena.length()>=6) 
        {
            //Puntuacion = 3 * largo de la cadena
            puntuacion = 3 * cadena.length();
            
            //Puntuacion = puntuacion + [2*total de mayusculas ingresadas]
            int numMayusculas=0;
            for (int i = 0; i < cadena.length(); i++) 
            {
                char c;
                c=cadena.charAt(i);
                if (Character.isUpperCase(c))
                {
                    numMayusculas++;
                } 
            }
            puntuacion = puntuacion+ (2*numMayusculas);
            
            //Puntuacion = puntuacion + [total de letras ingresadas +1]
            int numLetras =0;
            for (int i = 0; i < cadena.length(); i++) 
            {
                char c;
                c=cadena.charAt(i);
                if (Character.isLetter(c))
                {
                    numLetras++;
                } 
            }
            if (numLetras==cadena.length())
            {
                puntuacion=puntuacion-6;
            }
            puntuacion = puntuacion+ (1+numLetras);
            
            //Puntuacion = puntuacion + [2 + numNumeros]
            int numNumeros =0;
            for (int i = 0; i < cadena.length(); i++) 
            {
                char c;
                c=cadena.charAt(i);
                if (Character.isDigit(c))
                {
                    numNumeros++;
                } 
            }
            if (numNumeros==cadena.length()) 
            {
                puntuacion=puntuacion-3;
            }
            puntuacion = puntuacion+ (2+numNumeros);
            
            // Puntuacion = puntuacion + (total de simbolos ingresados) * [(Largo de la cadena) + (4)]
            int numSimbolos =0;
            for (int i = 0; i < cadena.length(); i++) 
            {
                char c;
                c=cadena.charAt(i);
                if ((c == '/')||(c == '¿')||(c == '?')||(c == '%')||(c == '$')||(c == '#'))
                {
                    numSimbolos++;
                } 
            }
            puntuacion = puntuacion + numSimbolos*(cadena.length()+4);
            String punteo = ""+puntuacion;
            
            
            //Rangos de contrasenñas 
            if ((puntuacion>=0)&&(puntuacion<=25)) 
            {
             lblRango.setText("Contraseña Insegura");
             lblRango.setForeground(Color.red);
            }
            if ((puntuacion>=26)&&(puntuacion<=35)) 
            {
                banderaPassword=true;    
             lblRango.setText("Contraseña Poco Segura");
             lblRango.setForeground(Color.orange);
            }
            if ((puntuacion>=36)&&(puntuacion<=50)) 
            {
                banderaPassword=true;  
             lblRango.setText("Contraseña Segura");
             lblRango.setForeground(Color.yellow);
            }
            if ((puntuacion>=51)) 
            {
                banderaPassword=true;  
             lblRango.setText("Contraseña muy segura");
             lblRango.setForeground(Color.green);
            }
        }
        else
        {
            //JOptionPane.showMessageDialog(rootPane, "No se puede ingresar una contraseña que contenga menos o igual a 6 caracteres");
            lblRango.setText("La contraseña tiene que ser mayor a 6 caracteres");
            lblRango.setForeground(Color.red);
        }
        return banderaPassword;
    }
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFotografia;
    private javax.swing.JButton btnRegistrarNuevoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelcorreo;
    private javax.swing.JTextPane lblComprobarTel;
    private javax.swing.JTextPane lblRango;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtPathFotografia;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
